### PR TITLE
Simplify post-checkout

### PR DESCRIPTION
**Pull request by alexeyten**
Use exit code instead of parsing stdout.
Also use `[` instead of `[[` bash-ism.

### CODE REVIEW

**Comment by MeFoDy** [comment]
Thank you for you PR.

But it looks like my code is just not optimal, not incorrect. Do I really need to change it? It's not an SH tutorial, it's a tip for frontend developers.

**Comment by alexeyten** [comment]
Well, people will copy it. So it would be better to copy good code, not bad one.

**Comment by MeFoDy** [comment]
Why do you think my code is bad? Is it incorrect? Has it any side-effects?

I don't mind of fixing the mistakes. But if there are no mistakes here, it's just an author's opinion.

**Comment by alexeyten** [comment]
It just smells bad. Unnecessary bashism (all other examples use plain `sh`). Checking for side effect text output instead of checking return code.

**Comment by MeFoDy** [comment]
Thank you!

**Pull request merged**
